# Generated by Django 5.2.8 on 2026-03-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название турнира')),
                ('game', models.CharField(choices=[('CS2', 'Counter-Strike 2'), ('Dota 2', 'Dota 2'), ('Valorant', 'Valorant'), ('Apex', 'Apex Legends'), ('Other', 'Другое')], max_length=20, verbose_name='Дисциплина')),
                ('image', models.ImageField(upload_to='tournaments/', verbose_name='Постер турнира')),
                ('description', models.TextField(verbose_name='Описание и правила')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Макс. участников')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tournament')},
            },
        ),
    ]
