# Generated by Django 5.2.8 on 2026-03-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournament_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменена пользователем'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_no_show',
            field=models.BooleanField(default=False, verbose_name='Штраф (Не пришел)'),
        ),
        migrations.AddField(
            model_name='user',
            name='strikes',
            field=models.IntegerField(default=0, verbose_name='Штрафы (Неявки)'),
        ),
    ]
