# Generated by Django 5.2.8 on 2026-03-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_is_cancelled_booking_is_no_show_user_strikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='strikes',
        ),
    ]
