# Generated by Django 5.2.8 on 2026-03-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_strikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка (английскими)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='computer',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='core.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='computer',
            unique_together={('zone', 'number')},
        ),
    ]
